//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketingServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaign
    {
        public int SubscriptionID { get; set; }
        public System.DateTime Date { get; set; }
        public string ProductID { get; set; }
        public int Day { get; set; }
        public bool ProductPurchased { get; set; }
        public bool Ended { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Subscription Subscription { get; set; }
    }
}
