//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketingServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignLog
    {
        public int SubscriptionID { get; set; }
        public System.DateTime Date { get; set; }
        public int CampaignID { get; set; }
        public int Day { get; set; }
        public System.Guid CustomerID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Campaign Campaign { get; set; }
        public virtual Subscription Subscription { get; set; }
    }
}
