//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketingServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineItem
    {
        public int transactionId { get; set; }
        public string itemNo { get; set; }
        public string productTitle { get; set; }
        public bool shippable { get; set; }
        public bool recurring { get; set; }
        public double accountAmount { get; set; }
        public int quantity { get; set; }
        public string downloadUrl { get; set; }
        public string lineItemType { get; set; }
    
        public virtual Transaction Transaction { get; set; }
    }
}
