//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketingServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.CampaignRecords = new HashSet<CampaignRecord>();
            this.EmailCampaigns = new HashSet<EmailCampaign>();
            this.ProductBanners = new HashSet<ProductBanner>();
            this.ProductFilters = new HashSet<ProductFilter>();
            this.ProductVideos = new HashSet<ProductVideo>();
        }
    
        public string ID { get; set; }
        public string Name { get; set; }
        public int NicheID { get; set; }
        public string HopLink { get; set; }
        public int Order { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public bool Active { get; set; }
        public Nullable<int> VendorID { get; set; }
        public double Price { get; set; }
        public bool Featured { get; set; }
        public string Sku { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampaignRecord> CampaignRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailCampaign> EmailCampaigns { get; set; }
        public virtual Nich Nich { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductBanner> ProductBanners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductFilter> ProductFilters { get; set; }
        public virtual Vendor Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductVideo> ProductVideos { get; set; }
    }
}
