//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketingServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefreshToken
    {
        public string ID { get; set; }
        public string ClientID { get; set; }
        public string Ticket { get; set; }
        public System.DateTime Expires { get; set; }
    }
}
