//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketingServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public int ID { get; set; }
        public string AccessToken { get; set; }
        public System.DateTime AccessTokenExpires { get; set; }
        public string RefreshToken { get; set; }
        public System.DateTime RefreshTokenExpires { get; set; }
    }
}
