//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketingServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaction()
        {
            this.LineItems = new HashSet<LineItem>();
        }
    
        public int id { get; set; }
        public System.DateTime transactionTime { get; set; }
        public string receipt { get; set; }
        public string transactionType { get; set; }
        public string vendor { get; set; }
        public string affiliate { get; set; }
        public string role { get; set; }
        public double totalAccountAmount { get; set; }
        public string paymentMethod { get; set; }
        public double totalOrderAmount { get; set; }
        public double totalTaxAmount { get; set; }
        public double totalShippingAmount { get; set; }
        public string currency { get; set; }
        public string orderLanguage { get; set; }
        public Nullable<System.Guid> customerId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LineItem> LineItems { get; set; }
    }
}
