//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketingServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Upsell
    {
        public int id { get; set; }
        public string upsellOriginalReceipt { get; set; }
        public int upsellFlowId { get; set; }
        public string upsellSession { get; set; }
        public string upsellPath { get; set; }
    }
}
